# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerCommonService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServerCommonService.proto',
  package='platformserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19ServerCommonService.proto\x12\x0eplatformserver2\x15\n\x13ServerCommonServiceb\x06proto3')
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SERVERCOMMONSERVICE = _descriptor.ServiceDescriptor(
  name='ServerCommonService',
  full_name='platformserver.ServerCommonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=45,
  serialized_end=66,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_SERVERCOMMONSERVICE)

DESCRIPTOR.services_by_name['ServerCommonService'] = _SERVERCOMMONSERVICE

# @@protoc_insertion_point(module_scope)
