# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc



class ServerCommonServiceStub(object):
  """option java_multiple_files = true;
  option java_package = "com.szwdcloud.platformserver.proto.platformserver";
  option java_outer_classname = "ServerCommonServiceProto";
  ///////////////////////////////response//////////////////////////////////////
  公共服务模块通用服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """


class ServerCommonServiceServicer(object):
  """option java_multiple_files = true;
  option java_package = "com.szwdcloud.platformserver.proto.platformserver";
  option java_outer_classname = "ServerCommonServiceProto";
  ///////////////////////////////response//////////////////////////////////////
  公共服务模块通用服务
  """


def add_ServerCommonServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'platformserver.ServerCommonService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
