# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CCCommonMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CCCommonMessage.proto',
  package='customercenter',
  syntax='proto3',
  serialized_options=_b('\n1com.szwdcloud.customercenter.proto.customercenterB\024CCCommonMessageProtoP\001'),
  serialized_pb=_b('\n\x15\x43\x43\x43ommonMessage.proto\x12\x0e\x63ustomercenter\x1a\x19google/protobuf/any.proto\"{\n\x0f\x43\x43\x42\x61tchDataPage\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pagesize\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\x14\n\x0ctotalRecords\x18\x04 \x01(\x02\x12\"\n\x04rows\x18\x05 \x03(\x0b\x32\x14.google.protobuf.Any\"8\n\x16\x43\x43\x44\x61taPageRequestParam\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pagesize\x18\x02 \x01(\x05\";\n\x0b\x41\x64\x64ressList\x12,\n\taddressVo\x18\x01 \x03(\x0b\x32\x19.customercenter.AddressVo\"y\n\tAddressVo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nprovinceId\x18\x02 \x01(\t\x12\x14\n\x0cprovinceName\x18\x03 \x01(\t\x12\x0e\n\x06\x63ityId\x18\x04 \x01(\t\x12\x10\n\x08\x63ityName\x18\x05 \x01(\t\x12\x14\n\x0c\x64istrictName\x18\x06 \x01(\t\"#\n\x13RequestListProvince\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"%\n\x0fRequestListCity\x12\x12\n\nprovinceId\x18\x01 \x01(\t\"%\n\x13RequestListDistrict\x12\x0e\n\x06\x63ityId\x18\x01 \x01(\t2\x83\x02\n\rCommonService\x12R\n\x0clistProvince\x12#.customercenter.RequestListProvince\x1a\x1b.customercenter.AddressList\"\x00\x12J\n\x08listCity\x12\x1f.customercenter.RequestListCity\x1a\x1b.customercenter.AddressList\"\x00\x12R\n\x0clistDistrict\x12#.customercenter.RequestListDistrict\x1a\x1b.customercenter.AddressList\"\x00\x42K\n1com.szwdcloud.customercenter.proto.customercenterB\x14\x43\x43\x43ommonMessageProtoP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_CCBATCHDATAPAGE = _descriptor.Descriptor(
  name='CCBatchDataPage',
  full_name='customercenter.CCBatchDataPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='customercenter.CCBatchDataPage.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='customercenter.CCBatchDataPage.pagesize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='customercenter.CCBatchDataPage.offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalRecords', full_name='customercenter.CCBatchDataPage.totalRecords', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='customercenter.CCBatchDataPage.rows', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=191,
)


_CCDATAPAGEREQUESTPARAM = _descriptor.Descriptor(
  name='CCDataPageRequestParam',
  full_name='customercenter.CCDataPageRequestParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='customercenter.CCDataPageRequestParam.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='customercenter.CCDataPageRequestParam.pagesize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=249,
)


_ADDRESSLIST = _descriptor.Descriptor(
  name='AddressList',
  full_name='customercenter.AddressList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addressVo', full_name='customercenter.AddressList.addressVo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=310,
)


_ADDRESSVO = _descriptor.Descriptor(
  name='AddressVo',
  full_name='customercenter.AddressVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='customercenter.AddressVo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provinceId', full_name='customercenter.AddressVo.provinceId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provinceName', full_name='customercenter.AddressVo.provinceName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cityId', full_name='customercenter.AddressVo.cityId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cityName', full_name='customercenter.AddressVo.cityName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='districtName', full_name='customercenter.AddressVo.districtName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=433,
)


_REQUESTLISTPROVINCE = _descriptor.Descriptor(
  name='RequestListProvince',
  full_name='customercenter.RequestListProvince',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='customercenter.RequestListProvince.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=470,
)


_REQUESTLISTCITY = _descriptor.Descriptor(
  name='RequestListCity',
  full_name='customercenter.RequestListCity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provinceId', full_name='customercenter.RequestListCity.provinceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=509,
)


_REQUESTLISTDISTRICT = _descriptor.Descriptor(
  name='RequestListDistrict',
  full_name='customercenter.RequestListDistrict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cityId', full_name='customercenter.RequestListDistrict.cityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=548,
)

_CCBATCHDATAPAGE.fields_by_name['rows'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ADDRESSLIST.fields_by_name['addressVo'].message_type = _ADDRESSVO
DESCRIPTOR.message_types_by_name['CCBatchDataPage'] = _CCBATCHDATAPAGE
DESCRIPTOR.message_types_by_name['CCDataPageRequestParam'] = _CCDATAPAGEREQUESTPARAM
DESCRIPTOR.message_types_by_name['AddressList'] = _ADDRESSLIST
DESCRIPTOR.message_types_by_name['AddressVo'] = _ADDRESSVO
DESCRIPTOR.message_types_by_name['RequestListProvince'] = _REQUESTLISTPROVINCE
DESCRIPTOR.message_types_by_name['RequestListCity'] = _REQUESTLISTCITY
DESCRIPTOR.message_types_by_name['RequestListDistrict'] = _REQUESTLISTDISTRICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CCBatchDataPage = _reflection.GeneratedProtocolMessageType('CCBatchDataPage', (_message.Message,), dict(
  DESCRIPTOR = _CCBATCHDATAPAGE,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.CCBatchDataPage)
  ))
_sym_db.RegisterMessage(CCBatchDataPage)

CCDataPageRequestParam = _reflection.GeneratedProtocolMessageType('CCDataPageRequestParam', (_message.Message,), dict(
  DESCRIPTOR = _CCDATAPAGEREQUESTPARAM,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.CCDataPageRequestParam)
  ))
_sym_db.RegisterMessage(CCDataPageRequestParam)

AddressList = _reflection.GeneratedProtocolMessageType('AddressList', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSLIST,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.AddressList)
  ))
_sym_db.RegisterMessage(AddressList)

AddressVo = _reflection.GeneratedProtocolMessageType('AddressVo', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSVO,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.AddressVo)
  ))
_sym_db.RegisterMessage(AddressVo)

RequestListProvince = _reflection.GeneratedProtocolMessageType('RequestListProvince', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTLISTPROVINCE,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.RequestListProvince)
  ))
_sym_db.RegisterMessage(RequestListProvince)

RequestListCity = _reflection.GeneratedProtocolMessageType('RequestListCity', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTLISTCITY,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.RequestListCity)
  ))
_sym_db.RegisterMessage(RequestListCity)

RequestListDistrict = _reflection.GeneratedProtocolMessageType('RequestListDistrict', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTLISTDISTRICT,
  __module__ = 'CCCommonMessage_pb2'
  # @@protoc_insertion_point(class_scope:customercenter.RequestListDistrict)
  ))
_sym_db.RegisterMessage(RequestListDistrict)


DESCRIPTOR._options = None

_COMMONSERVICE = _descriptor.ServiceDescriptor(
  name='CommonService',
  full_name='customercenter.CommonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=551,
  serialized_end=810,
  methods=[
  _descriptor.MethodDescriptor(
    name='listProvince',
    full_name='customercenter.CommonService.listProvince',
    index=0,
    containing_service=None,
    input_type=_REQUESTLISTPROVINCE,
    output_type=_ADDRESSLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listCity',
    full_name='customercenter.CommonService.listCity',
    index=1,
    containing_service=None,
    input_type=_REQUESTLISTCITY,
    output_type=_ADDRESSLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listDistrict',
    full_name='customercenter.CommonService.listDistrict',
    index=2,
    containing_service=None,
    input_type=_REQUESTLISTDISTRICT,
    output_type=_ADDRESSLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMONSERVICE)

DESCRIPTOR.services_by_name['CommonService'] = _COMMONSERVICE

# @@protoc_insertion_point(module_scope)
